### PR TITLE
Initial master/PR build CI

### PR DESCRIPTION
**Pull request by redmushie**
## `ci-master`
- Build `master` branch in production mode
  - Also triggers for PRs into the `master` branch
- Builds container, tags as `master`
- Pushes container only if it was not a PR

## `ci-develop`
- Builds `develop` branch in development mode
  - Also triggers for PRs into the `develop` branch
- Builds container, tags as `develop`
- Pushes container only if it was not a PR

## `ci-tag`
- Builds branch in production mode
- Uploads `dist/` artifacts as ZIP file to the auto-generated tag release
- Builds container, tags as:
  - `v{{major}}.{{minor}}.{{patch}}`
  - `{{major}}.{{minor}}.{{patch}}`
  - `{{major}}.{{minor}}`
  - `{{major}}`
  - `latest`
- Pushes container

## Examples
Example of built containers: https://github.com/redmushie/ShockLink-WebUI/pkgs/container/shocklink-webui
Example pushes to `master`: https://github.com/redmushie/ShockLink-WebUI/commits/master
Example pushes to `develop`: https://github.com/redmushie/ShockLink-WebUI/commits/develop
Example pull request: https://github.com/redmushie/ShockLink-WebUI/pull/1
Example tag release: https://github.com/redmushie/ShockLink-WebUI/releases/tag/v0.0.11

### CODE REVIEW

**Comment by redmushie** [comment]
Apologies for the re-marking as draft, something broke at the last second. Ready for review now @LucHeart

**Comment by LucHeart** [comment]
no worries, please lmk if i need to setup secerts for it or anything.

Also, just wondering, why did you choose to build outside of the container and then copy into it?
docker multistep build is the alternative

**Comment by LucHeart** [comment]
Also, what do you mean by "push-tag" tag?

**Comment by redmushie** [comment]
> no worries, please lmk if i need to setup secerts for it or anything.

No additional setup should be needed for merging.

> Also, just wondering, why did you choose to build outside of the container and then copy into it? docker multistep build is the alternative

It wasn't a conscious decision. I suppose the difference is that the artifacts are now also usable outside of Docker, since they are uploaded as a ZIP archive to the tag release (in case of `push-tag.yml` specifically): https://github.com/redmushie/ShockLink-WebUI/releases/tag/v0.0.9

**Comment by redmushie** [comment]
> Also, what do you mean by "push-tag" tag?

Can you clarify? I don't understand the question.

**Comment by redmushie** [comment]
> And does it not push a new image if the merge is from a pull request or what does that mean?

`ci-develop` and `ci-master` both trigger for pull requests made towards their respective branches. However, this clause prevents it from trying to push to the registry:
image

So we basically test the full CI without the final side-effect.\

**Comment by LucHeart** [comment]
> > Also, what do you mean by "push-tag" tag?
> 
> Can you clarify? I don't understand the question.

What does push-tag do?

**Comment by redmushie** [comment]
> > > Also, what do you mean by "push-tag" tag?
> > 
> > 
> > Can you clarify? I don't understand the question.
> 
> What does push-tag do?

I suppose at this point in time `ci-tag` might be a better name for it. It does the same as `ci-master` and `ci-develop` with some tag-specific effects. It's triggered whenever a tag is pushed to the repository.

- It builds the project;
- Uploads the artifacts (`dist/` folder contents) as ZIP archive to the release (example: https://github.com/redmushie/ShockLink-WebUI/releases/tag/v0.0.9 );
- Builds the container using said artifacts;
- Pushes the container to the container registry.

The built container is tagged as described in the original post:
- `v{{major}}.{{minor}}.{{patch}}`
- `{{major}}.{{minor}}.{{patch}}`
- `{{major}}.{{minor}}`
- `{{major}}`
- `latest`

To see what that looks like, take a look here: https://github.com/redmushie/ShockLink-WebUI/pkgs/container/shocklink-webui

**Pull request merged**
